language: go
go:
    - 1.3
notifications:
    irc:
        channels:
            - "irc.mozilla.org#datapipeline"
before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x
    - sudo apt-get update -q
    - sudo apt-get install protobuf-compiler cmake libgeoip-dev

install:
    - bash bin/build_pipeline_heka.sh

script:
    - cd build/heka
    - . env.sh
    - cd build
    - make test
    - go test github.com/mozilla-services/data-pipeline/heka/plugins/s3splitfile
