[hekad]
base_dir = "."
share_dir = "."

[ProtobufDecoder]

[PipelineInput]
type = "TcpInput"
address = "127.0.0.1:30231"
decoder = "ProtobufDecoder"

[Dashboard]
type = "DashboardOutput"
address = ":4352"
static_directory = "build/heka/dasher"
ticker_interval = 10

[CounterFilter]
message_matcher = "Type == 'http_edge_incoming'"
ticker_interval = 1

[PayloadEncoder]

[LogOutput]
message_matcher = "Type == 'heka.counter-output'"
encoder = "PayloadEncoder"

[RequestRates]
type = "SandboxFilter"
message_matcher = "Type == 'http_edge_incoming'"
filename = "examples/request_rates.lua"
ticker_interval = 60
preserve_data = true
output_limit = 256000

[ProtobufEncoder]

[ArchiveOutput]
type = "FileOutput"
path = "./data_pipeline.out"
use_framing = true
message_matcher = "Type == 'http_edge_incoming'"
encoder = "ProtobufEncoder"
