[hekad]
base_dir = "."
share_dir = "."

[RstEncoder]

[TestInput]
type = "HttpListenInput"
address = "127.0.0.1:8080"
request_headers = ["Content-Length", "X-Forwarded-For"]

[RawOutput]
# Print the raw incoming http messages
type = "LogOutput"
message_matcher = "TRUE"
encoder = "RstEncoder"

[PipelineOutput]
# Encode the messages according to the HTTP Edge Server spec.
type = "TcpOutput"
address = "127.0.0.1:30231"
use_framing = true
message_matcher = "TRUE"
encoder = "HttpEdgeEncoder"

[HttpEdgeEncoder]
type = "SandboxEncoder"
filename = "heka/sandbox/encoders/http_edge_encoder.lua"
memory_limit = 90000000
output_limit = 2097152
    [HttpEdgeEncoder.config]
    geoip_city_db = "GeoLiteCity.dat"
    namespace_config = '{"test":{"logger":"test_input","max_path_length":20480,"max_data_length":1048576},"telemetry":{"dimensions":["reason","appName","appVersion","appUpdateChannel","appBuildID"],"max_path_length":10240,"max_data_length":204800}}'
